#!/usr/bin/env bash
# Generated by `sbb account add __NAME__`. Owns one account's config dirs and pane tags.
# Never touches ~/.zshrc, the keychain or credential files: log in once per account by hand.
set -euo pipefail

BASE="$HOME/.ai-account-__NAME__"
CODEX_DIR="$BASE/codex"
CLAUDE_DIR="$BASE/claude"
PREFERRED_SHELL="${__ENV___SHELL:-/bin/zsh}"
WORK_DIR="${__ENV___WORKDIR:-$HOME}"

if [ ! -x "$PREFERRED_SHELL" ]; then
  PREFERRED_SHELL="${SHELL:-/bin/bash}"
fi

mkdir -p "$CODEX_DIR" "$CLAUDE_DIR"

export CODEX_HOME="$CODEX_DIR"
export CLAUDE_CONFIG_DIR="$CLAUDE_DIR"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:$HOME/.local/bin:$PATH"
export CLAUDE_CODE_MAX_OUTPUT_TOKENS="64000"

# Tag only the pane tmux handed us in $TMUX_PANE. Never fall back to the server's
# current pane: a script that inherited $TMUX (tests, hooks, background jobs) would
# otherwise retag a real pane that belongs to someone else.
if [ -n "${TMUX_PANE:-}" ] && command -v tmux >/dev/null 2>&1; then
  # Stamp the pane tag with the pid that owns this account env: `env` hands it to
  # the pane shell, every other subcommand execs into $$. The status script drops
  # the tag once that pid is gone, so a respawned pane reports the root account.
  if [ "${1:-shell}" = "env" ]; then
    AI_OWNER_PID="$(tmux display-message -p -t "$TMUX_PANE" '#{pane_pid}' 2>/dev/null || true)"
  else
    AI_OWNER_PID="$$"
  fi
  tmux set-option -p -t "$TMUX_PANE" @codex_home "$CODEX_DIR" >/dev/null 2>&1 || true
  tmux set-option -p -t "$TMUX_PANE" @ai_account "__TAG__" >/dev/null 2>&1 || true
  tmux set-option -p -t "$TMUX_PANE" @ai_pane_pid "$AI_OWNER_PID" >/dev/null 2>&1 || true
fi

# Keep Codex credentials per-account instead of macOS keychain.
if [ ! -f "$CODEX_HOME/config.toml" ]; then
  printf 'cli_auth_credentials_store = "file"\n' > "$CODEX_HOME/config.toml"
fi

case "${1:-}" in
  codex)
    shift
    exec codex "$@"
    ;;
  claude)
    shift
    exec claude "$@"
    ;;
  env)
    printf 'export CODEX_HOME="%s"\nexport CLAUDE_CONFIG_DIR="%s"\n' \
      "$CODEX_HOME" "$CLAUDE_CONFIG_DIR"
    printf 'export CLAUDE_CODE_MAX_OUTPUT_TOKENS="%s"\n' \
      "$CLAUDE_CODE_MAX_OUTPUT_TOKENS"
    ;;
  shell|"")
    shift || true
    cd "$WORK_DIR"
    exec "$PREFERRED_SHELL" -l
    ;;
  *)
    echo "usage: ai-__NAME__ {codex|claude|shell|env}"
    exit 2
    ;;
esac
